language: node_js
node_js:
- node
sudo: false
script:
- npm run test
- npm run coverage
- npm run build
after_success:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info
addons:
  code_climate:
    repo_token: 6c2f65bed4a8ff50c04a9ac4c6cc3744d0ec2ddad9ef7c19e2aa4f74457562ee
deploy:
  provider: npm
  email: stephen.austin@rovisys.com
  api_key:
    secure: CoMLNW6nBbchAvXnxksrJyVod5oEqWRCxrB/cAAxm5bFA7IS3+Sp/r0QMvjcrMuTkskByDu/tZp2JsB3uNZsfJBenFNMczbj80o9sPbTO96zxrdrdd7UQzfIHyC/CXeAtgiAvR7pWLOloFwtMzcMvsP7JwK0YA7IUKBMwq10k+EMB16fp3o5q/JyUvhrCP8Aup24Sfbvr71fcqiffUlbQ8BuGQ22BYXHF5IGio0M1VfAR5RedRWkLLEysOSAoi7zqnlM8rlh+X/H650ertAXAaH30up8KYACHuUMlN0cvvfLEIXNYct3sFHKybK2lfUYOLLj7ulNose76VEaQ2uovd1YhBpbemXEcw09lLAXboI3SweJ3SvAXeZhIBQI9o0GthSxKLdEPecOU/LGHooGPSCSExe3kK0XChlHe2vQe3ZByv2Nr136p164+JAeQW9pg+gCQFLuqNt5mJd47ky9WvZbKXp9e/xuPZH44ipnet1F+jrjvdRCi99D5jq2A2klWE8XGLIAQZU2Q79mihWAgnM+0bCsme+Xcyw2hjaTakL+wZPrUlmdtsBUllFHfm0QIb7IoYlqvNiSeEsWqpuJDv4LcN5OHLwSyojmQd8UOcTfwY5j/GooYsMz2iw/1ScyXQzb5DTagr5FywXV6kNuxhRgkGxxV3Sx2Eje6KhLKnA=
  on:
    tags: true
    repo: RoviSys/react-ref-decorator
